### ISSUE TITLE
Can't open the post

### ISSUE THREAD

**Issue by ForNeVeR** [JaredWright/jaredwright.github.io#2]
When opening http://jaredwright.github.io/2015/11/10/An-Introduction-To-The-Windows-Filtering-Platform.html all I can see in an empty page :(

**Comment by JaredWright** [comment]
I could not figure out why this post stopped working, even after reverting the whole repository back to a stable commit where it was working. I moved this content over into the example driver project [here](https://github.com/JaredWright/WFPStarterKit/tree/master/Tutorial)
